try {
throw new Error('error occured!');
}catch (e) {
    console.log('catch error');
}